<?php

namespace app\controllers;

use Yii;
use app\models\Config;
use common\helpers\HttpClient;
use common\helpers\Util;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\HttpBasicAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\auth\QueryParamAuth;
use yii\helpers\Json;
use yii\rest\ActiveController;

class MerchandiseController extends ActiveController
{
    public $modelClass = 'app\models\User';
    public $serializer = [
        'class' => 'yii\rest\Serializer',
        'collectionEnvelope' => 'items',
    ];

    /**
     * @throws \yii\base\InvalidConfigException
     */
    public function init()
    {
        parent::init();
        \Yii::$app->user->enableSession = false;
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['corsFilter'] = [
            'class' => \yii\filters\Cors::className(),
            'cors' => [
                // restrict access to
                'Origin' => \Yii::$app->params['allowOrigin'],
                'Access-Control-Request-Method' => \Yii::$app->params['accessControlRequestMethod'],
                'Access-Control-Allow-Credentials' => true,
                // Allow OPTIONS caching
                'Access-Control-Max-Age' => \Yii::$app->params['accessControlMaxAge'],
                'Access-Control-Expose-Headers' => \Yii::$app->params['accessControlExposeHeaders'],
                'Access-Control-Allow-Headers' => \Yii::$app->params['accessControlAllowHeaders'],
            ],
        ];
        $behaviors['authenticator'] = [
            'class' => CompositeAuth::className(),
            'authMethods' => [
                HttpBasicAuth::className(),
                HttpBearerAuth::className(),
                QueryParamAuth::className(),
            ],
        ];
        //$behaviors['rateLimiter']['enableRateLimitHeaders'] = false;
        return $behaviors;
    }

    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }

    /**
     * 商品推荐
     * @return array|mixed
     */
    public function actionApiWares()
    {
        $url = Config::ADV_API_URL . '/api/wares/get/url';
        $wareModel = strval(Yii::$app->request->get('wareModel'));
        $wareType = intval(Yii::$app->request->get('wareType'));
        $httpClient = new HttpClient();
        $data = $httpClient->get($url, [
            'wareModel' => $wareModel,
            'wareType' => $wareType
        ]);
        Yii::debug(Json::encode($data));
        return Util::parseHttpClientWaresData($data);
    }

    public function checkAccess($action, $model = null, $params = [])
    {
        parent::checkAccess($action, $model, $params); // TODO: Change the autogenerated stub
    }
}