<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "config".
 *
 * @property int $id ID
 * @property int $uid UID
 * @property string $config_key CONFIG KEY
 * @property string $config_entity CONFIG ENTITY
 * @property string $created_at 创建时间
 */
class Config extends \yii\db\ActiveRecord
{

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'config';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['uid', 'config_key'], 'required'],
            [['uid'], 'integer'],
            [['config_entity'], 'string'],
            [['created_at'], 'safe'],
            [['config_key'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'uid' => Yii::t('app', 'UID'),
            'config_key' => Yii::t('app', 'CONFIG KEY'),
            'config_entity' => Yii::t('app', 'CONFIG ENTITY'),
            'created_at' => Yii::t('app', '创建时间'),
        ];
    }

    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     * @return ConfigQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ConfigQuery(get_called_class());
    }
}
