<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "device".
 *
 * @property int $id ID
 * @property int $uid UID
 * @property string $serial_number 序列号
 * @property string $mac_address MAC 地址
 * @property double $lng 经度
 * @property double $lat 纬度
 * @property string $created_at 创建时间
 * @property string $updated_at 更新时间
 * @property int $status 设备状态
 * @property string $device_config 设备配置
 */
class Device extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'device';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['uid', 'serial_number', 'mac_address'], 'required'],
            [['uid', 'status'], 'integer'],
            [['lng', 'lat'], 'number'],
            [['created_at', 'updated_at'], 'safe'],
            [['device_config'], 'string'],
            [['serial_number', 'mac_address'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'uid' => Yii::t('app', 'UID'),
            'serial_number' => Yii::t('app', '序列号'),
            'mac_address' => Yii::t('app', 'MAC 地址'),
            'lng' => Yii::t('app', '经度'),
            'lat' => Yii::t('app', '纬度'),
            'created_at' => Yii::t('app', '创建时间'),
            'updated_at' => Yii::t('app', '更新时间'),
            'status' => Yii::t('app', '设备状态'),
            'device_config' => Yii::t('app', '设备配置'),
        ];
    }

    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     * @return DeviceQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new DeviceQuery(get_called_class());
    }
}
