<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "face".
 *
 * @property int $id ID
 * @property int $device_id 设备 ID
 * @property int $file_manage_id 文件 ID
 * @property string $created_at 创建时间
 * @property string $face_detected_result 识别结果
 * @property string $merchandise_result 商品推荐结果
 */
class Face extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'face';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['device_id', 'file_manage_id', 'created_at', 'face_detected_result', 'merchandise_result'], 'required'],
            [['device_id', 'file_manage_id'], 'integer'],
            [['created_at'], 'safe'],
            [['face_detected_result', 'merchandise_result'], 'string'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'device_id' => Yii::t('app', '设备 ID'),
            'file_manage_id' => Yii::t('app', '文件 ID'),
            'created_at' => Yii::t('app', '创建时间'),
            'face_detected_result' => Yii::t('app', '识别结果'),
            'merchandise_result' => Yii::t('app', '商品推荐结果'),
        ];
    }

    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     * @return FaceQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new FaceQuery(get_called_class());
    }
}
