<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "file_manage".
 *
 * @property int $id ID
 * @property int $device_id 设备 ID
 * @property string $raw_name 原始名称
 * @property string $unique_name URL名称
 * @property string $created_at 创建时间
 * @property string $detail 详情
 */
class FileManage extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'file_manage';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['device_id', 'raw_name', 'unique_name'], 'required'],
            [['device_id'], 'integer'],
            [['created_at'], 'safe'],
            [['detail'], 'string'],
            [['raw_name', 'unique_name'], 'string', 'max' => 255],
            [['unique_name'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'device_id' => Yii::t('app', '设备 ID'),
            'raw_name' => Yii::t('app', '原始名称'),
            'unique_name' => Yii::t('app', 'URL名称'),
            'created_at' => Yii::t('app', '创建时间'),
            'detail' => Yii::t('app', '详情'),
        ];
    }

    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     * @return FileManageQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new FileManageQuery(get_called_class());
    }
}
