<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "rule".
 *
 * @property int $id ID
 * @property int $uid UID
 * @property int $rule_key RULE KEY
 * @property int $rule_condition RULE CONDITION
 * @property int $rule_value RULE VALUE
 * @property int $created_at 创建时间
 * @property int $status 状态
 */
class Rule extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'rule';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['uid', 'rule_key', 'rule_condition', 'rule_value', 'created_at', 'status'], 'required'],
            [['uid', 'rule_key', 'rule_condition', 'rule_value', 'created_at', 'status'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'uid' => Yii::t('app', 'UID'),
            'rule_key' => Yii::t('app', 'RULE KEY'),
            'rule_condition' => Yii::t('app', 'RULE CONDITION'),
            'rule_value' => Yii::t('app', 'RULE VALUE'),
            'created_at' => Yii::t('app', '创建时间'),
            'status' => Yii::t('app', '状态'),
        ];
    }

    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     * @return RuleQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new RuleQuery(get_called_class());
    }
}
